# See https://github.com/jderusse/docker-gitsplit

splits:
  - prefix: "src/Core"
    target: "https://${GH_TOKEN}@github.com/acmephp/core.git"
  - prefix: "src/Ssl"
    target: "https://${GH_TOKEN}@github.com/acmephp/ssl.git"

origins:
  - ^master$
  - ^\d+\.\d+\.\d+(-(alpha|beta|rc)\d)?$
