vcs:
  name: git
  sign-tag: true

version-generator:
  name: semantic
  allow-label: true

version-persister: vcs-tag

prerequisites:
  working-copy-check: ~
  display-last-changes: ~

pre-release-actions:
  changelog-update:
    format: custom
    file: CHANGELOG.md
    dump-commits: true
  vcs-commit: ~
