name: Continuous integration (release)
on:
  push:
    branches:
      - master
jobs:
  build_container:
    name: Build container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        tools: box
    - uses: ramsey/composer-install@v3
    - name: Build PHAR
      run: box compile
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.3.0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v6.0.0
      with:
        context: build/
        file: Dockerfile
        push: true
        load: true
        tags: "ghcr.io/${{ github.repository }}/acmephp:master-${{ github.sha }}"
    - name: Confirm that we can run ACME php via docker
      run: docker run --rm ghcr.io/${{ github.repository }}/acmephp:master-${{ github.sha }}
permissions:
  packages: write
  contents: read
